language: node_js
node_js: node
after_success: npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: JpNUxXTedOsHbpYbavsg0ceyq+7dMZlif/imh25clzpBJjmHWUcInOdSUQnTC8kvAMl7jvT11fNmJJj5Hz/J7AoA2N70RmzJOAKT0Qp09KOr4gNUMbrPFW/eSiTg6iZXSp+NUcXBl4ZF0nae80t7tHbPzVqSH8pSO3WWPeGyS/+Rc37sDlraXlXxg7hHzev8vJi7IOssD3LZSp/+p2TccC5x2v8QVd3BJ6CukH8PHfbDjQylwl3TzWBuc+Mi9GEUSolEC+Id5f8gF4moVTtAwVj8yqa3R2poCp5b/2+DtCZkYqu+8aD8Cy1QCFo382QlOqCuexk/U15aI01BVhnedCPPMZURenplgWzvfd2onz3/6/Qca2oxtaLp3P4+R83WSdaZU8azmDL8frH9iMoO09FjK7D/uQxBsN19SbMgMRXjx/46hnwowocqaQsn9n3RlVYP335VnPNKey3FOf8Ji3v52nkVAkIjV5fN2lgSyjxyTn4XauPc0oXiAax967DuNIhvYztYlwL8WijB+2iTSseS/x5GrYoOpv3rtTHSSLlEdSdBthCrg6XQN3FDWeq9nBr5UtWwEDfiHKNQfWMes06n41sjrIJgZNubwzY8otcve9uBJRL6RQM/o4SI5gfeIN6Esnb60yD2mKsOX8xlRefrD8Yr6Ob0ZuZGnLA+3kQ=
  on:
    tags: true
    all_branches: true
    repo: Brightspace/frau-local-appresolver
