language: node_js
node_js: node
after_success: npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 48d8......fb35
    secure: hHtYc3xOnlzqnsTrT33zIIgtkdwLRgaabfuPw51HvRBaiFmjuIWZqckabae36TaizuQzXkqRWyEy6uBfoIlyQ+ubSCJTNYzFu3laWnnGH+VzHXMI7NQfa5oAXMeGUyhHJC/Am9GKjkw2Om+Y8HhN1oEa6d3kPfPqmFLZl37PR+r26kJfiiSfjn1NfsNyqafiAMbB4QbKtV2rPKSAc75NjXc5HxlSU+g6aPBkop6nBQyCqzFAZ1Bu4vlmhBTfemhzvBmlhO0lMJVbwKV9cF2LX5u9AzdHFysl/DO+ORLbtqz6NkPOfpnoyQxupIAov/p2Qy0w9sU+CQbfAnsawMvryg13jgUyQGJ36YhqJPFaX3XEd5kfZQv9KesBXXTO/5OJLOksjLjXKgezlaUrrwG+Wx6ofSHcnuHFD0L0cHIhbZ06N4U6qDpSegn7eCmB2Nq3YSuDjmo3ctJPV3UCCNtIyc1P4dIEYexxRSe+8gHN79P7ix+jldatSsPEtFFIUpaWb/nJFib7ZKCIq5zCiRw4+kObBGM7wFOgp8dZ3RiHj6FmDO/jtGODLwnmAZZb3pClsEdNERU2HB6vwo4AeUv6rNn3P/7dOlNdE5Sbl8ZRcXcRq838y82nUIK4blKLMVln2uQYQG0kWLsSg2FUoERganTs4e04IWSxQve7aCcibJ8=
  on:
    tags: true
    all_branches: true
    repo: Brightspace/frau-local-appresolver
